djangoDelivery/apps/delivery/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views


# router = routers.DefaultRouter()
# router.register(r'rests', views.RestsViewSet)
# router.register(r'prods', views.ProdsViewSet)
# router.register(r'basket', views.BasketViewSet)
# router.register(r'register', views.UserViewSet)

app_name = 'delivery'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:restaurant_id>/', views.detail, name='detail'),
    path('info/<int:product_id>', views.info, name='info'),
    path('basket', views.basket, name='basket'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('basket_adding/', views.basket_adding, name='basket_adding'),
    # path('api/v1/', include(router.urls)),
    # path('api/v1/auth/', include('rest_framework.urls')),
]

djangoDelivery/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from django.conf import settings
from rest_framework import routers

# from apps.delivery import views

# router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)
# router.register(r'advices', views.AdviceViewSet, basename='advices')

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     # re_path('(?P<lang>(ru|en))/', include(router.urls)),
#     path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
# ]

urlpatterns = [
    path('delivery/', include('delivery.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoDelivery/apps/delivery/models.py
from django.db import models
from django.db.models.signals import post_save
from simple_history.models import HistoricalRecords


class Restaurant(models.Model):
    restaurant_name = models.CharField('Название ресторана', max_length=200, blank=True, null=True, default=None)
    restaurant_rating = models.CharField('Рейтинг ресторана', max_length=10, blank=True, null=True, default=None)
    rest_image = models.ImageField(upload_to='rest_images/', blank=True, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return '%s' % self.restaurant_name

    class Meta:
        verbose_name = 'Ресторан'
        verbose_name_plural = 'Рестораны'


class Product(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True, default=None)
    product_image = models.ImageField(upload_to='products_images/', blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    product_name = models.CharField('Название блюда', max_length=64, blank=True, null=True, default=None)
    product_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return '%s' % self.product_name

    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'


class Courier(models.Model):
    courier_name = models.CharField('Имя курьера', max_length=64, blank=True, null=True, default=None)
    courier_phone = models.CharField('Номер курьера', max_length=24, blank=True, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return '%s' % self.courier_name

    class Meta:
        verbose_name = 'Курьер'
        verbose_name_plural = 'Курьеры'


class Status(models.Model):
    name = models.CharField(max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказов'


class Order(models.Model):
    # courier = models.ForeignKey(Courier, on_delete=models.SET_DEFAULT)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    # customer_name = models.CharField('Имя заказчика', max_length=64, blank=True, null=True, default=None)
    # customer_email = models.EmailField('Почта заказчика', blank=True, null=True, default=None)
    # customer_phone = models.CharField('Номер заказчика', max_length=12, blank=True, null=True, default=None)
    # customer_address = models.CharField('Номер заказчика', max_length=128, blank=True, null=True, default=None)
    comments = models.TextField(blank=True, null=True, default=None)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return f'Заказ №{self.id}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    num = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    def save(self, *args, **kwargs):
        price_per_item = self.product.product_price
        self.price_per_item = price_per_item
        self.total_price = self.num * price_per_item

        super(ProductInOrder, self).save(*args, **kwargs)


def products_in_order_post_save(sender, instance, created, **kwargs):
    order = instance.order
    all_products_in_order = ProductInOrder.objects.filter(order=order, is_active=True)
    order_total_price = 0
    for item in all_products_in_order:
        order_total_price += item.total_price
    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)


post_save.connect(products_in_order_post_save, sender=ProductInOrder)


class ProductInBasket(models.Model):
    user_id = models.CharField(max_length=32, blank=True, null=True, default=None)
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    num = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return '%s' % self.product.product_name

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'

    def save(self, *args, **kwargs):
        price_per_item = self.product.product_price
        self.price_per_item = price_per_item
        self.total_price = int(self.num) * price_per_item

        super(ProductInBasket, self).save(*args, **kwargs)

djangoDelivery/apps/delivery/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

djangoDelivery/apps/delivery/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseRedirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from rest_framework import generics, viewsets, status
from rest_framework.decorators import action
from rest_framework.exceptions import ValidationError, NotFound
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated

from .models import Restaurant, Product, ProductInBasket
from .forms import CreateUserForm
from django.contrib import messages

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .permissions import IsAdminOrReadOnly
from .serializers import RestaurantSerializer, ProdInBasketSerializer, ProductSerializer, UserSerializer, \
    PasswordSerializer


class RestsViewSet(viewsets.ModelViewSet):
    queryset = Restaurant.objects.all()
    serializer_class = RestaurantSerializer
    permission_classes = [IsAdminOrReadOnly, ]


class ProdsViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [IsAdminOrReadOnly, ]
    filter_backends = [OrderingFilter, SearchFilter]
    search_fields = ['product_name']
    ordering_fields = ['product_price']


class FilterBackend(ProdsViewSet):
    def get_filtered(self):
        prods = Product.objects.get(Q(product_price__gt=1000) & Q(restaurant__startswith='Э'))
        queryset = self.serializer_class(prods, many=True)
        return Response(queryset)


class BasketViewSet(viewsets.ModelViewSet):
    queryset = ProductInBasket.objects.all()
    serializer_class = ProdInBasketSerializer
    permission_classes = (IsAuthenticated, )

    @action(methods=['get'], detail=False)
    def prods(self, request):
        user = request.user.id
        prods = ProductInBasket.objects.filter(user_id=user)
        queryset = ProdInBasketSerializer(prods, many=True)
        return Response(queryset.data)

    @action(methods=['post'], detail=False)
    def add(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({'message': 'ok'})


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = PasswordSerializer

    @action(detail=True, methods=['post'])
    def set_password(self, request, pk=None):
        user = self.get_object()
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            user.set_password(serializer.data.get['new_password'])
            user.save()
            return Response({'message': 'ok'})
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    @action(methods=['post'], detail=False, url_path='register')
    def register(self, request):
        if '@' not in request.data['email']:
            raise ValidationError({'error': 'email isn\'t correct'})
        if len(request.data['login']) < 6:
            raise ValidationError({'error': 'minimum login length 6 characters'})
        if len(request.data['password']) < 6:
            raise ValidationError({'error': 'minimum password length 6 characters'})
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({'message': 'ok'})


def register(request):
    if request.user.is_authenticated:
        return redirect('delivery:index')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, f'Аккаунт для {user} создан!')
                return redirect('delivery:login')
        context = {'form': form}
        return render(request, 'delivery/register.html', context)


def login_user(request):
    if request.user.is_authenticated:
        return redirect('delivery:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username,  password=password)
            if user is not None:
                login(request, user)
                return redirect('delivery:index')
            else:
                messages.info(request, 'Неверный логин или пароль')
        context = {}
        return render(request, 'delivery/login.html', context)


def logout_user(request):
    logout(request)
    return redirect('delivery:login')


@login_required(login_url='login')
def index(request):
    # restaurant_list = Restaurant.objects.all()
    # print(Response({'rests': RestaurantSerializer(restaurant_list, many=True).data}))
    # return render(request, 'delivery/list.html', {'restaurant_list': restaurant_list})
    restaurant_list = Restaurant.objects.all()
    res = RestaurantSerializer(restaurant_list, many=True).data
    res_list = {'restaurant_list': res}
    return render(request, 'delivery/list.html', res_list)


@login_required(login_url='login')
class RestView(APIView):
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    template_name = 'delivery/list.html'

    def get(self, request):
        queryset = Restaurant.objects.all()
        serialized_data = RestaurantSerializer(queryset, many=True).data
        return render(request, self.template_name, {'restaurant_list': serialized_data})
        # return render_to_response(template_name, {'data': queryset.data})
        # return Response({'restaurant_list': queryset})

    # def get(self, request):
    #     r = Restaurant.objects.all()
    #     return Response({'rests': RestaurantSerializer(r, many=True).data})


@login_required(login_url='login')
def detail(request, restaurant_id):
    try:
        rest = Restaurant.objects.get(id=restaurant_id)
    except:
        raise Http404('Ресторан не найден!')

    products_list = rest.product_set.all()
    return render(request, 'delivery/detail.html', {'restaurant': rest, 'products_list': products_list})


@login_required(login_url='login')
def info(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
    except:
        raise Http404('Блюдо не найдено!')

    return render(request, 'delivery/info.html', {'product': product, 'rest_id': product.restaurant})


@login_required(login_url='login')
def basket(request):
    return render(request, 'delivery/basket.html')


def basket_adding(request):
    return_dict = {}
    print('!!!')
    print(request.POST)
    data = request.POST
    product_id = data.get('product_id')
    num = data.get('num')
    user_id = request.user.id
    is_delete = data.get('is_delete')
    if is_delete == 'true':
        ProductInBasket.objects.filter(id=product_id).update(is_active=False)
    else:
        new_product, created = ProductInBasket.objects.get_or_create(user_id=user_id,
                                                                     product_id=product_id, defaults={'num': num},
                                                                     is_active=True)
        if not created:
            new_product.num += int(num)
            new_product.save(force_update=True)

    products_total_num = ProductInBasket.objects.filter(user_id=user_id, is_active=True).count()
    return_dict['products_total_num'] = products_total_num
    print('!!!!!!', return_dict)
    return JsonResponse(return_dict)

djangoDelivery/templates/delivery/basket.html
{% extends 'base.html' %}

{% block title %}{{dish.dish_name}}{% endblock %}

{% block content %}

<div class="basket">
    <h2>Корзина</h2>
    <form action="" method="DELETE" id="delete-form" class="basket__form">
        {% csrf_token %}
        <table class="basket__table">
            <thead>
                <tr>
                    <th>Название товара</th>
                    <th>Количество</th>
                    <th>Цена за единицу</th>
                    <th>Общая цена</th>
                </tr>
            </thead>
            <tbody>
                {% for prod in products_in_basket %}
                    <tr>
                        <td>
                            {{ prod.product.product_name }}
                        </td>
                        <td>
                            <input type="number" value="{{ prod.num }}">
                        </td>
                        <td>
                            {{ prod.price_per_item }}
                        </td>
                        <td>
                            <span class="total_prod_amount">
                                {{ prod.total_price }}
                            </span>
                        </td>
                        <td>
                            <form method="POST" action="{% url 'delivery:basket_adding' %}" id="delete-form">
                                {% csrf_token %}
                                <button type="submit" id="delete-item" class="delete-item" data-product_id="{{ prod.id }}">Удалить</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="order-sum">
                <b>Итого: </b><span id="total_order_amount"></span>
        </div>
        <div class="order-btn">
            <button class="custom-btn btn-6"><span>Заказать</span></button>
        </div>
    </form>
</div>

{% endblock %}

djangoDelivery/templates/delivery/detail.html
{% extends 'base.html' %}

{% block title %}{{restaurant.restaurant_name}}{% endblock %}

{% block content %}

<h2 class="rest-name">{{restaurant.restaurant_name}}</h2>
<div class="raiting-wrapper">
    <img src="/static/img/star.svg" alt="star image" class="raiting-wrapper__star">
    <p class="raiting-wrapper__num">{{restaurant.restaurant_rating}}</p>
</div>


{% if products_list %}
    <!-- <div class="product-wrapper"> -->
    <div class="product-wrapper">
        {% for prod in products_list %}
            <div class="product-wrapper__card" style="width: 18rem;">
                <a href="{% url 'delivery:info' prod.id %}">
                    <img src="/media/{{ prod.product_image }}" alt="product image" class="product-wrapper__img">
                </a>
                <div class="product-wrapper__card-body">
                    <a href="{% url 'delivery:info' prod.id %}"><p class="product-wrapper__card-title">{{prod.product_name}}</p></a>
                    <p class="product-wrapper__price">{{prod.product_price}} руб.</p>
                    <!-- btn btn-primary w-100 p-auto -->
                    <form method="POST" action="{% url 'delivery:basket_adding' %}" id="detail-form"> {% csrf_token %}
                        <button class="custom-btn btn-6 detail-submit" id="detail-submit" type="submit"
                            data-product_id="{{ prod.id }}"
                            data-num="1">В корзину</button>
                    </form>
                </div>
            </div>
        
        {% endfor %}
    </div>
{% else %}
<p style="text-align: center;">Здесь ничего нет!</p>

{% endif %}

{% endblock %}

djangoDelivery/templates/delivery/info.html
{% extends 'base.html' %}

{% block title %}{{dish.dish_name}}{% endblock %}

{% block content %}

<h2>{{product.product_name}}</h2>
<div class="info-wrapper">
    <img src="/media/{{ product.product_image }}" class="info-wrapper__img">
    <div class="info-wrapper__container" >
        <p class="info-wrapper__price">{{product.product_price}} руб.</p>
        <div class="info-wrapper__buy-wrapper">
            <form id="buy-product" action="{% url 'delivery:basket_adding' %}" class="info-wrapper__form">
                {% csrf_token %}
                <input type="number" name="number" id="number">
                <button type="submit" id="submit-btn" class="info-wrapper__btn"
                    data-product_id="{{ product.id }}"
                    data-name="{{ product.product_name }}"
                    data-price="{{ product.product_price }}"
                >В корзину</button>
            </form>
            </div>
                <p class="info-wrapper__deskription">{{ product.description }}</p>
            </div>
        </div>

{% endblock %}

djangoDelivery/templates/delivery/list.html
{% extends 'base.html' %}

{% block title %} Рестораны {% endblock %}

{% block content %}
    <div class="form-wrapper">
        <form class="form-wrapper__search">
            <input type="text" placeholder="Введите название ресторана">
            <button type="submit" class="form-wrapper__btn">Найти</button>
        </form>
    </div>
    <div class="rest-wrapper">
        {% for item in restaurant_list %}
            <a href="{% url 'delivery:detail' item.id %}">
                <div class="rest-wrapper__rest-card-wrapper">
                    <img src="{{ item.rest_image }}" class="rest-wrapper__img" alt="restaurant image">
                    <p class="rest-wrapper__title">{{item.restaurant_name}}</p>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

djangoDelivery/templates/delivery/login.html
<style>
h2 {
    margin-top: 70px;
    margin-bottom: 50px;
    text-align: center;
}
.form {
    margin: auto;
    max-width: 400px;
    width: 100%;
    min-height: 180px;
    padding: 15px;
    border: 1px solid black;
    text-align: center;
    border-radius: 10px;
    box-shadow: 0 0 10px 10px rgba(0, 0, 0, 0.2);
}
.form__item {
    width: 100%;
    display: flex;
    justify-content: space-between;
    margin-bottom: 20px;
}
input {
    width: 70%;
}
.form__btn {
    border: 2px solid black;
    padding: 10px 15px;
    background-color: white;
    cursor: pointer;
    margin-top: 30px;
}
.form__btn:hover {
    transition: .3s;
    background-color: black;
    color: white;
}
.after-form {
    text-align: center;
    margin-top: 50px;
}
</style>

<h2>Войти</h2>
<form method="POST" class="form">
    {% csrf_token %}
    <div class="form__item" class="form__item"><label for="">Логин </label><input type="text" name="username" placeholder="Логин"></div>
    <div class="form__item" class="form__item"><label for="">Пароль </label><input type="password" name="password" placeholder="Пароль"></div>
    <button type="submit" class="form__btn">Войти</button>
</form>
{% for message in messages %}
    <p id="messages">{{ message }}</p>
{% endfor %}
<div class="after-form">
    Нет аккаунта? <a href="{% url 'delivery:register' %}">Зарегистрируйтесь</a>
</div>

djangoDelivery/templates/delivery/register.html
<style>
h2 {
    margin-top: 70px;
    margin-bottom: 50px;
    text-align: center;
}
.form {
    margin: auto;
    max-width: 400px;
    width: 100%;
    min-height: 230px;
    padding: 15px;
    border: 1px solid black;
    text-align: center;
    border-radius: 10px;
    box-shadow: 0 0 10px 10px rgba(0, 0, 0, 0.2);
}
.form__item {
    width: 100%;
    display: flex;
    justify-content: space-between;
    margin-bottom: 20px;
}
.form__btn {
    border: 2px solid black;
    padding: 10px 15px;
    background-color: white;
    cursor: pointer;
}
.form__btn:hover {
    transition: .3s;
    background-color: black;
    color: white;
}
.after-form {
    text-align: center;
    margin-top: 50px;
}
</style>

<h2>Регистрация</h2>
<form method="POST" class="form">
    {% csrf_token %}
    <div class="form__item">
        {{ form.username.label }}
        {{ form.username }}
    </div>
    <div class="form__item">
        {{ form.email.label }}
        {{ form.email }}
    </div>
    <div class="form__item">
        {{ form.password1.label }}
        {{ form.password1 }}
    </div>
    <div class="form__item">
        {{ form.password2.label }}
        {{ form.password2 }}
    </div>
    <input type="submit" name="createUser" class="form__btn">
</form>

{{ form.errors }}

<div class="after-form">
    Уже есть аккаунт? <a href="{% url 'delivery:login' %}">Войти</a>
</div>

<!-- <form class="login-form" action="">
    <h2>Регистрация</h2>
    <div class="form-input-material">
        {{ form.username.label }}
        {{ form.username }}
        <input type="text" name="username" id="username" placeholder="Логин" autocomplete="off" class="form-control-material" required />
        <label for="username">Логин</label>
    </div>
    <div class="form-input-material">
        {{ form.email.label }}
        {{ form.email }}
        <input type="email" name="email" id="email" placeholder="Почта" autocomplete="off" class="form-control-material" required />
        <label for="username">Почта</label>
    </div>
    <div class="form-input-material">
        {{ form.password1.label }}
        {{ form.password1 }}
        <input type="password" name="password1" id="password1" placeholder="Пароль" autocomplete="off" class="form-control-material" required />
        <label for="password">Пароль</label>
    </div>
    <div class="form-input-material">
        {{ form.password2.label }}
        {{ form.password2 }}
        <input type="password" name="password2" id="password2" placeholder="Пароль" autocomplete="off" class="form-control-material" required />
        <label for="password">Повторите пароль</label>
    </div>
    <button type="submit" class="btn btn-primary btn-ghost">Login</button>
</form> -->

<script>
    var form_fields = document.getElementsByTagName('input');
    form_fields[1].placeholder = 'Логин';
    form_fields[2].placeholder = 'Почта';
    form_fields[3].placeholder = 'Пароль';
    form_fields[4].placeholder = 'Повторите пароль';
</script>